@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNocmlzIiwiaWQiOiI2OTI1ZmUwMTQwNTVlYTJmNmU1MGQxMjEiLCJpYXQiOjE3NjQwOTc2MzUsImV4cCI6MTc2NDEwMTIzNX0.wDNYxIRC_dV9mP1H4nXK9U0bLzzpBvmQ7YRgWkXkx5M
###
POST http://localhost:4300/api/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"Mouse",
    "shortDescription":"Logitech mouse",
    "longDescription":"Logitech mouse MX Master 3",
    "price":123.99,
    "salePrice":99.99,
    "onSale":false,
    "qty":10
}

###
POST http://localhost:4300/api/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"Keyboard",
    "shortDescription":"Logitech keyboard",
    "longDescription":"Logitech keyboard G513",
    "price":129.99,
    "salePrice":109.99,
    "onSale":true,
    "qty":25
}

###
POST http://localhost:4300/api/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name":"Mouse",
    "shortDescription":"Apple magic mouse",
    "longDescription":"Apple magic mouse bluetooth",
    "price":89.99
}

###
POST http://localhost:4300/api/products
Content-Type: application/json

{
    "name":"Graphics Card ",
    "shortDescription":"NVidia Geforce RTX 3090",
    "longDescription":"NVidia Geforce RTX 3090",
    "price":1499.99
}

###
POST http://localhost:4300/api/products
Content-Type: application/json

{
    "name":"Graphics Card ",
    "shortDescription":"NVidia Geforce RTX 3080",
    "longDescription":"NVidia Geforce RTX 3080",
    "price":699.99,
    "qty":5
}

###
GET http://localhost:4300/api/products

###
@id=6925fef24055ea2f6e50d12d

GET http://localhost:4300/api/products/{{id}}